[package]
name = "pitgun-source-physics"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1"
csv = "1"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1"
pitgun-contract = { path = "../pitgun-contract" }
pitgun-core = { path = "../pitgun-core" }
pitgun-codec-json = { path = "../pitgun-codec-json" }
pitgun-codec-udp = { path = "../pitgun-codec-udp" }
pitgun-signing = { path = "../pitgun-signing" }
reqwest = { version = "0.11", features = ["blocking", "json"] }
socket2 = "0.5"
tungstenite = "0.21"
url = "2"
