# yaml-language-server: $schema=https://pitgun.io/schemas/pipeline-manifest/v1

manifest_version: 1

source:
  type: udp
  bind_addr: "0.0.0.0"
  port: 5001

processors:
  - type: channel_filter
    channels: ["NLap", "nEngine"]

  - type: segment_aggregate
    segment_key: "NLap"
    targets:
      - channel: "nEngine"
        metrics: ["count", "min", "max", "mean", "sum", "stddev"]
    emit_on_change: true
    emit_last_segment_on_eof: true

sink:
  type: console
