//! Canonical evidence emitted by the Racing Simulator workload.

use std::fmt;

use pitgun_contract::{
    ArtifactIdentity, CanonicalJsonError, CatalogReleaseIdentityV1, DeterministicRunContractV1,
    Digest, ExecutionId, ExecutionReceiptV1, RunBundleReceiptV1, RuntimeIdentity,
    SignedRunAuthorizationV1, TelemetrySummaryError, TelemetrySummaryV1, canonical_json_bytes,
    canonical_json_digest,
};
use serde::{Deserialize, Serialize};

use crate::{RaceOutput, RacingCatalogSnapshot, RunRaceInput, StandingStatus};

/// Wire version of the browser-to-WASM hosted execution request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
pub enum RacingHostedExecutionRequestVersion {
    /// First signed Racing browser execution semantics.
    #[serde(rename = "pitgun.racing-hosted-execution/v1")]
    V1,
}

/// Strict browser request for one Authority-authorized Racing execution.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RacingHostedExecutionRequestV1 {
    /// Exact request wire semantics.
    pub schema_version: RacingHostedExecutionRequestVersion,
    /// Authority response for the exact deterministic contract.
    pub signed_authorization: SignedRunAuthorizationV1,
    /// Canonical Racing input bound by the signed contract.
    pub input: RunRaceInput,
    /// Unique UUIDv7 generated by the browser for this concrete attempt.
    pub execution_id: ExecutionId,
    /// SHA-256 of the exact WASM module bytes loaded by the browser.
    pub wasm_artifact_digest: Digest,
}

/// Wire version of explicit catalog-backed execution lineage.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
pub enum RacingExecutionResolutionVersion {
    /// First lineage block for a catalog-owned model-parameter resource.
    #[serde(rename = "pitgun.racing-execution-resolution/v1")]
    V1,
    /// Lineage block supporting an exact reviewed thermal-family profile.
    #[serde(rename = "pitgun.racing-execution-resolution/v2")]
    V2,
    /// Lineage block supporting component-composed vehicle resources.
    #[serde(rename = "pitgun.racing-execution-resolution/v3")]
    V3,
}

/// Exact immutable resources selected for one catalog-backed Racing execution.
///
/// The signed run contract already binds `model` and `simulation_pack`. This
/// explicit projection makes the complete lineage inspectable and lets the
/// Verifier fail closed on a missing or substituted execution resource.
#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RacingExecutionResolutionV1 {
    /// Exact lineage wire semantics.
    pub schema_version: RacingExecutionResolutionVersion,
    /// Immutable catalog release from which execution resources were resolved.
    pub catalog_release: CatalogReleaseIdentityV1,
    /// Exact Simulation Pack identity signed into the run contract.
    pub simulation_pack: ArtifactIdentity,
    /// Exact statically linked executable model identity.
    pub model: ArtifactIdentity,
    /// Semantic version and digest of exact model-parameter resource bytes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_parameters: Option<ArtifactIdentity>,
    /// Semantic version and digest of the exact thermal-family profile bytes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thermal_family_profile: Option<ArtifactIdentity>,
    /// Exact thermal profile resolved from installed power-unit identities.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub power_unit_thermal_profile: Option<ArtifactIdentity>,
    /// Exact component-to-capability mapping used by execution and clients.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub component_capability_profile: Option<ArtifactIdentity>,
}

impl RacingExecutionResolutionV1 {
    /// Projects the exact execution-affecting resources selected by a catalog.
    #[must_use]
    pub fn from_catalog(catalog: &RacingCatalogSnapshot, model: &ArtifactIdentity) -> Option<Self> {
        let model_parameters = catalog.model_parameters_identity().cloned();
        let thermal_family_profile = catalog.thermal_family_profile_identity().cloned();
        let power_unit_thermal_profile = catalog.power_unit_thermal_profile_identity().cloned();
        let component_capability_profile = catalog.component_capability_profile_identity().cloned();
        if model_parameters.is_none()
            && thermal_family_profile.is_none()
            && power_unit_thermal_profile.is_none()
            && component_capability_profile.is_none()
        {
            return None;
        }
        Some(Self {
            schema_version: if power_unit_thermal_profile.is_some()
                || component_capability_profile.is_some()
            {
                RacingExecutionResolutionVersion::V3
            } else if thermal_family_profile.is_some() {
                RacingExecutionResolutionVersion::V2
            } else {
                RacingExecutionResolutionVersion::V1
            },
            catalog_release: catalog.release_identity().clone(),
            simulation_pack: catalog.manifest().simulation_pack.identity.clone(),
            model: model.clone(),
            model_parameters,
            thermal_family_profile,
            power_unit_thermal_profile,
            component_capability_profile,
        })
    }
}

/// Complete evidence payload accepted by the hosted Racing Verifier.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RacingVerificationSubmissionV1 {
    /// Authority-issued authorization for the exact deterministic contract.
    pub signed_authorization: SignedRunAuthorizationV1,
    /// Exact canonical input whose digest is bound by the signed contract.
    pub input: RunRaceInput,
    /// Concrete execution receipt produced by this browser attempt.
    pub receipt: RunBundleReceiptV1,
    /// Canonical Racing domain output produced by that execution.
    pub output: RacingOutputV1,
    /// Canonical domain-neutral summary of the execution telemetry.
    pub telemetry_summary: TelemetrySummaryV1,
    /// Explicit lineage for releases with separately resolved model resources.
    ///
    /// Historical submissions omit this field and retain their exact wire
    /// representation. A catalog containing model parameters or a reviewed
    /// thermal-family profile requires it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_resolution: Option<RacingExecutionResolutionV1>,
}

impl pitgun_runtime::WorkloadEvidence for RacingRunEvidenceV1 {
    fn output_digest(&self) -> Result<Digest, CanonicalJsonError> {
        RacingRunEvidenceV1::output_digest(self)
    }

    fn telemetry_summary_digest(&self) -> Result<Digest, CanonicalJsonError> {
        RacingRunEvidenceV1::telemetry_summary_digest(self)
    }
}

/// Wire version of the canonical Racing domain output.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum RacingOutputVersion {
    /// Racing result fields covered by the first portable-exact contract.
    #[serde(rename = "pitgun.racing-output/v1")]
    V1,
}

/// Canonical status of one Racing competitor.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RacingStandingStatusV1 {
    /// The competitor completed the run.
    Finished,
    /// The competitor did not finish for the supplied stable reason.
    Dnf { reason: String },
    /// The competitor was disqualified for the supplied stable reason.
    Dsq { reason: String },
}

/// Canonical standing included in the versioned Racing domain output.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RacingStandingV1 {
    /// Stable competitor identifier supplied by the run input.
    pub competitor_id: String,
    /// One-based finishing position.
    pub position: u32,
    /// Total elapsed race time in milliseconds.
    pub total_time_ms: u64,
    /// Best completed lap time in milliseconds.
    pub best_lap_ms: u64,
    /// Number of completed laps.
    pub laps_completed: u16,
    /// Gap to the leader in milliseconds.
    pub gap_to_leader_ms: u64,
    /// Final status of the competitor.
    pub status: RacingStandingStatusV1,
}

/// Complete canonical Racing result, excluding the separately summarized stream.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RacingOutputV1 {
    /// Version controlling the canonical wire representation.
    pub schema_version: RacingOutputVersion,
    /// Final standings in finishing order.
    pub standings: Vec<RacingStandingV1>,
    /// Total elapsed time of the player race in milliseconds.
    pub total_time_ms: u64,
    /// Laps on which the player entered the pits.
    pub player_pit_laps: Vec<u16>,
    /// Player lap times in chronological order, in milliseconds.
    pub player_lap_times_ms: Vec<u64>,
}

/// Canonical domain output and telemetry evidence produced by one Racing run.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RacingRunEvidenceV1 {
    /// Canonical domain result used to calculate `output_digest`.
    pub output: RacingOutputV1,
    /// Domain-neutral stream summary used to calculate `telemetry_summary_digest`.
    pub telemetry_summary: TelemetrySummaryV1,
}

/// Failures produced while constructing or hashing Racing evidence.
#[derive(Debug)]
pub enum RacingEvidenceError {
    /// A batch count cannot be represented by the summary schema.
    BatchCountOverflow,
    /// Telemetry aggregation violated a V1 summary invariant.
    TelemetrySummary(TelemetrySummaryError),
    /// Canonical serialization of one evidence artifact failed.
    CanonicalJson(CanonicalJsonError),
}

impl fmt::Display for RacingEvidenceError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::BatchCountOverflow => formatter.write_str("Racing batch count overflowed u64"),
            Self::TelemetrySummary(error) => error.fmt(formatter),
            Self::CanonicalJson(error) => error.fmt(formatter),
        }
    }
}

impl std::error::Error for RacingEvidenceError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::BatchCountOverflow => None,
            Self::TelemetrySummary(error) => Some(error),
            Self::CanonicalJson(error) => Some(error),
        }
    }
}

impl From<TelemetrySummaryError> for RacingEvidenceError {
    fn from(error: TelemetrySummaryError) -> Self {
        Self::TelemetrySummary(error)
    }
}

impl From<CanonicalJsonError> for RacingEvidenceError {
    fn from(error: CanonicalJsonError) -> Self {
        Self::CanonicalJson(error)
    }
}

impl RacingRunEvidenceV1 {
    /// Projects the mutable runtime output into the stable V1 evidence schemas.
    pub fn from_race_output(output: &RaceOutput) -> Result<Self, RacingEvidenceError> {
        let batch_count = u64::try_from(output.player_batches.len())
            .map_err(|_| RacingEvidenceError::BatchCountOverflow)?;
        let frames = output
            .player_batches
            .iter()
            .flat_map(|batch| batch.frames.iter());
        let telemetry_summary = TelemetrySummaryV1::from_ordered_frames(batch_count, frames, 0)?;

        let standings = output
            .standings
            .iter()
            .map(|standing| RacingStandingV1 {
                competitor_id: standing.competitor_id.clone(),
                position: standing.position,
                total_time_ms: standing.total_time_ms,
                best_lap_ms: standing.best_lap_ms,
                laps_completed: standing.laps_completed,
                gap_to_leader_ms: standing.gap_to_leader_ms,
                status: match &standing.status {
                    StandingStatus::Finished => RacingStandingStatusV1::Finished,
                    StandingStatus::Dnf { reason } => RacingStandingStatusV1::Dnf {
                        reason: reason.clone(),
                    },
                    StandingStatus::Dsq { reason } => RacingStandingStatusV1::Dsq {
                        reason: reason.clone(),
                    },
                },
            })
            .collect();

        Ok(Self {
            output: RacingOutputV1 {
                schema_version: RacingOutputVersion::V1,
                standings,
                total_time_ms: output.total_time_ms,
                player_pit_laps: output.player_pit_laps.clone(),
                player_lap_times_ms: output.player_lap_times_ms.clone(),
            },
            telemetry_summary,
        })
    }

    /// Returns RFC 8785 bytes for the complete V1 Racing domain result.
    pub fn canonical_output_bytes(&self) -> Result<Vec<u8>, CanonicalJsonError> {
        canonical_json_bytes(&self.output)
    }

    /// Returns RFC 8785 bytes for the domain-neutral telemetry summary.
    pub fn canonical_telemetry_summary_bytes(&self) -> Result<Vec<u8>, CanonicalJsonError> {
        canonical_json_bytes(&self.telemetry_summary)
    }

    /// Calculates the complete canonical Racing output digest.
    pub fn output_digest(&self) -> Result<Digest, CanonicalJsonError> {
        canonical_json_digest(&self.output)
    }

    /// Calculates the canonical telemetry summary digest.
    pub fn telemetry_summary_digest(&self) -> Result<Digest, CanonicalJsonError> {
        canonical_json_digest(&self.telemetry_summary)
    }

    /// Binds these canonical artifacts to one concrete execution receipt.
    pub fn execution_receipt(
        &self,
        contract: &DeterministicRunContractV1,
        execution_id: ExecutionId,
        runtime: RuntimeIdentity,
    ) -> Result<ExecutionReceiptV1, CanonicalJsonError> {
        ExecutionReceiptV1::for_contract(
            contract,
            execution_id,
            runtime,
            self.output_digest()?,
            self.telemetry_summary_digest()?,
        )
    }
}
